# Generated by Django 3.2.6 on 2021-08-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=150)),
                ('year', models.DateField(default='2021')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('number_of_axles', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=500)),
                ('bed_type', models.PositiveSmallIntegerField(choices=[(1, 'Wood'), (2, 'Steel')], default=1)),
                ('bed_comments', models.CharField(max_length=5000)),
                ('current_tires_condition', models.PositiveSmallIntegerField(choices=[(1, '100%'), (2, '75%'), (3, '50%')], default=1)),
                ('has_spare_tire', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (3, 'No')], default=1)),
                ('number_of_ramps', models.IntegerField()),
                ('ramps_material', models.PositiveSmallIntegerField(choices=[(1, 'Aluminium'), (2, 'Steel')], default=1)),
                ('ramps_comments', models.CharField(max_length=5000)),
                ('electrical_instalation', models.CharField(max_length=5000)),
                ('price', models.IntegerField()),
                ('tax_price', models.IntegerField()),
                ('plate', models.CharField(max_length=50)),
                ('plate_stage', models.PositiveSmallIntegerField(choices=[(1, 'Temporary'), (2, 'Permanent')], default=1)),
                ('title_file', models.FileField(upload_to='titles')),
                ('title_note', models.CharField(default='', max_length=50)),
                ('sticker_file', models.FileField(upload_to='stickers')),
                ('sticker_note', models.CharField(default='', max_length=50)),
                ('Legal_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_legal_owner', to='towit.owners')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_owner', to='towit.owners')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_stage', to='towit.stage')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_stage', to='towit.stage')),
            ],
        ),
        migrations.CreateModel(
            name='TrailerPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='pictures')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_picture', to='towit.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('comments', models.CharField(max_length=5000)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_maintenance', to='towit.trailer')),
            ],
        ),
    ]
