# Generated by Django 3.2.6 on 2021-08-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='trailer',
            name='sticker_file',
            field=models.FileField(blank=True, upload_to='stickers'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='sticker_note',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='title_file',
            field=models.FileField(blank=True, upload_to='titles'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='title_note',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trailer',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trailer_type', to='towit.trailertype'),
            preserve_default=False,
        ),
    ]
