# Generated by Django 3.2.6 on 2021-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0002_auto_20210825_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='bed_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='electrical_instalation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='ramps_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='sticker_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='title_note',
            field=models.TextField(blank=True),
        ),
    ]
