# Generated by Django 3.2.6 on 2021-08-28 11:58

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0007_auto_20210828_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerpicture',
            name='image',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='towit/pictures'),
        ),
    ]
