# Generated by Django 3.2.6 on 2021-08-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0008_alter_trailerpicture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_status', to='towit.maintenancestatus'),
            preserve_default=False,
        ),
    ]
