# Generated by Django 3.2.6 on 2021-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0010_contact_interest_lease_leasestage_lessee_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='term_unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Weeks'), (2, 'Months')], default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='term',
            field=models.IntegerField(),
        ),
    ]
