# Generated by Django 3.2.6 on 2021-08-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0011_auto_20210829_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.RenameField(
            model_name='trailer',
            old_name='length',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='model',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='ramps_comments',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='width',
        ),
        migrations.AddField(
            model_name='trailer',
            name='ramps_length',
            field=models.PositiveSmallIntegerField(choices=[(1, '5'), (2, '6'), (3, '7'), (4, '8'), (5, '9')], default=1),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='has_spare_tire',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='number_of_axles',
            field=models.PositiveSmallIntegerField(choices=[(1, '2'), (2, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_color', to='towit.color'),
        ),
    ]
