# Generated by Django 3.2.7 on 2021-09-03 13:19

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0012_auto_20210830_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='location_file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='towit/locations'),
        ),
        migrations.AlterField(
            model_name='lessee',
            name='insurance_file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='towit/insurances'),
        ),
        migrations.AlterField(
            model_name='lessee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lessee',
            name='license_file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='towit/licenses'),
        ),
        migrations.AlterField(
            model_name='lessee',
            name='license_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='trailerpicture',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='towit/pictures'),
        ),
        migrations.CreateModel(
            name='HandWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='signatures')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_writing', to='towit.lease')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='towit/contracts')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_document', to='towit.lease')),
            ],
        ),
    ]
