# Generated by Django 3.2.7 on 2021-09-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0013_auto_20210903_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(blank=True)),
                ('emei', models.IntegerField()),
                ('device_password', models.CharField(default='123456', max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('phone_password', models.CharField(max_length=15)),
                ('line_credit', models.FloatField(blank=True)),
                ('logitude', models.FloatField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_trailer', to='towit.trailer')),
            ],
        ),
    ]
