# Generated by Django 3.2.7 on 2021-09-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0015_alter_tracker_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='line_credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='logitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
