# Generated by Django 3.2.7 on 2021-09-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0016_auto_20210909_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
