# Generated by Django 3.2.7 on 2021-09-10 13:39

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0017_rename_logitude_tracker_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='plate_file',
            field=models.FileField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='towit/plates'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='tax',
            field=models.PositiveSmallIntegerField(choices=[(1, 6.25), (2, 8.5)], default=1),
        ),
        migrations.AddField(
            model_name='trailer',
            name='tire_layers',
            field=models.PositiveSmallIntegerField(choices=[(1, '10'), (2, '14'), (3, '16')], default=1),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='phone_password',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
