# Generated by Django 3.2.7 on 2021-12-20 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0020_auto_20211111_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tracker',
            name='MAX_ERRORS',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tracker',
            name='SMART',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracker',
            name='TGPS',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tracker',
            name='TGPSB',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Tcheck',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Tint',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='tracker',
            name='TintB',
            field=models.IntegerField(default=360),
        ),
        migrations.AddField(
            model_name='tracker',
            name='Tsend',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tracker',
            name='TsendB',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tracker',
            name='pendingConfigs',
            field=models.BinaryField(default=b'\x00'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 18, 23, 20, 681449)),
        ),
    ]
