# Generated by Django 3.2.7 on 2021-12-24 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towit', '0021_auto_20211219_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='trackerdata',
            name='line_credit',
        ),
        migrations.AddField(
            model_name='tracker',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tracker_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='pendingConfigs',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 8, 18, 13, 676419)),
        ),
    ]
