# Generated by Django 3.2.7 on 2021-12-24 16:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towit', '0022_auto_20211224_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='emei',
            new_name='imei',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tracker_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 10, 6, 24, 40323)),
        ),
    ]
