# Generated by Django 3.2.7 on 2021-12-27 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0023_auto_20211224_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
