# Generated by Django 3.2.7 on 2022-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0024_alter_trackerdata_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerdata',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='trackerdata',
            name='powered',
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='heading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='power',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='sats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='year',
            field=models.DateField(default='2022'),
        ),
    ]
