# Generated by Django 3.2.7 on 2022-01-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0025_auto_20220109_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerdata',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
