# Generated by Django 3.2.11 on 2022-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0026_trackerdata_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='tracker',
            name='device_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
