# Generated by Django 3.2.11 on 2022-04-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0027_auto_20220217_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='line_credit',
        ),
        migrations.AddField(
            model_name='tracker',
            name='feed_traccar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tracker',
            name='traccar_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
