# Generated by Django 3.2.11 on 2022-05-27 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0028_auto_20220425_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerDebugData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_tracker', to='towit.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerDebugStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_reason', models.IntegerField(blank=True, null=True)),
                ('reset_cause', models.IntegerField(blank=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_startup', to='towit.trackerdebugdata')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerDebugGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sats', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('gps_delay', models.IntegerField(blank=True, null=True)),
                ('lte_delay', models.IntegerField(blank=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_gps', to='towit.trackerdebugdata')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerDebugError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_delay', models.IntegerField(blank=True, null=True)),
                ('lte_delay', models.IntegerField(blank=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debug_error', to='towit.trackerdebugdata')),
            ],
        ),
    ]
