# Generated by Django 4.1.2 on 2022-10-26 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0028_auto_20220425_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('charging', models.BooleanField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('wur', models.IntegerField(blank=True, null=True)),
                ('wdgc', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('LTE', 'Radio base'), ('GPS', 'GPS data')], default='LTE', max_length=3)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('mcc', models.IntegerField(blank=True, null=True)),
                ('mnc', models.IntegerField(blank=True, null=True)),
                ('lac', models.IntegerField(blank=True, null=True)),
                ('cellid', models.IntegerField(blank=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_upload', to='towit.tracker')),
            ],
        ),
    ]
