# Generated by Django 3.2.11 on 2022-05-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0029_trackerdebugdata_trackerdebugerror_trackerdebuggps_trackerdebugstartup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackerdebugerror',
            old_name='tracker',
            new_name='tdd',
        ),
        migrations.RenameField(
            model_name='trackerdebuggps',
            old_name='tracker',
            new_name='tdd',
        ),
        migrations.RenameField(
            model_name='trackerdebugstartup',
            old_name='tracker',
            new_name='tdd',
        ),
    ]
