# Generated by Django 4.1.2 on 2022-10-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0029_trackerupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Mode',
            field=models.CharField(choices=[('track', 'Tracking'), ('keep', 'Keepalived')], default='keep', max_length=5),
        ),
    ]
