# Generated by Django 3.2.11 on 2022-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0030_auto_20220527_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerdebugstartup',
            name='lte_delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
