# Generated by Django 3.2.11 on 2022-05-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0031_trackerdebugstartup_lte_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdebugerror',
            name='tdd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debug_error', to='towit.trackerdebugdata'),
        ),
        migrations.AlterField(
            model_name='trackerdebuggps',
            name='tdd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debug_gps', to='towit.trackerdebugdata'),
        ),
        migrations.AlterField(
            model_name='trackerdebugstartup',
            name='tdd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debug_startup', to='towit.trackerdebugdata'),
        ),
    ]
