# Generated by Django 4.1.2 on 2022-10-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0031_alter_tracker_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Mode',
            field=models.IntegerField(choices=[(0, 'Keepalived'), (1, 'Tracking')], default=0),
        ),
    ]
