# Generated by Django 3.2.11 on 2022-05-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0032_auto_20220527_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerdebugerror',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trackerdebuggps',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trackerdebugstartup',
            name='id',
        ),
        migrations.AlterField(
            model_name='trackerdebugerror',
            name='tdd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='towit.trackerdebugdata'),
        ),
        migrations.AlterField(
            model_name='trackerdebuggps',
            name='tdd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='towit.trackerdebugdata'),
        ),
        migrations.AlterField(
            model_name='trackerdebugstartup',
            name='tdd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='towit.trackerdebugdata'),
        ),
    ]
