# Generated by Django 3.2.11 on 2022-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0033_auto_20220527_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='lessee_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tracker',
            name='tracker_bin_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tracker',
            name='tracker_description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='TGPSB',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Tsend',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='TsendB',
            field=models.IntegerField(default=3),
        ),
    ]
