# Generated by Django 3.2.11 on 2022-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0034_auto_20221001_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='tracker_bin_number',
            new_name='trailer_bin_number',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='tracker_description',
            new_name='trailer_description',
        ),
    ]
