# Generated by Django 4.1.2 on 2022-10-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towit', '0032_alter_tracker_mode'),
        ('towit', '0035_auto_20221002_0829'),
    ]

    operations = [
    ]
