# Generated by Django 3.2.6 on 2021-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinreview',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
