# Generated by Django 3.2.6 on 2021-08-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contractinreview_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAccepted',
            fields=[
                ('contractinreview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contracts.contractinreview')),
            ],
            bases=('contracts.contractinreview',),
        ),
    ]
