# Generated by Django 3.2.6 on 2021-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20210823_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='inspection_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='year',
            field=models.DateField(default='2021'),
        ),
    ]
