from django.contrib import admin
from .models import *
from .model.tracker import *

admin.site.register(Trailer)
admin.site.register(Owners)
admin.site.register(Stage)
admin.site.register(TrailerType)
admin.site.register(Status)
admin.site.register(TrailerPicture)
admin.site.register(UserProfile)
admin.site.register(Maintenance)
admin.site.register(MaintenanceStatus)
admin.site.register(LeaseStage)
admin.site.register(Interest)
admin.site.register(Lease)
admin.site.register(Contact)
admin.site.register(Lessee)
admin.site.register(Person)
admin.site.register(Color)
admin.site.register(HandWriting)
admin.site.register(ContractDocument)
admin.site.register(Tracker)
admin.site.register(TrackerData)
admin.site.register(TrackerDebugData)
admin.site.register(TrackerDebugError)
admin.site.register(TrackerDebugGPS)
admin.site.register(TrackerDebugStartup)
admin.site.register(TrackerUpload)
